<?  /*  This is the style sheet. You can use HTML and PHP code here.
        It should be included from within the header file, in the <HEAD>
        section. If no header file is found, it will be included in
        the <HEAD> section generated by the script                            */ ?>

<style type="text/css">
<!--
   body { font-family: arial, verdana, trebuchet, times; text-decoration: none; color: <? echo $body_text_color ?>; }

   td { font-family: times, verdana, trebuchet, arial; text-decoration: none; color: <? echo $body_text_color ?>; }

   a:link { text-decoration: underline; color: <? echo $body_link_color ?>; }
   a:visited { text-decoration: underline; color: <? echo $body_link_color ?>; }
   a:hover { text-decoration: underline; color: <? echo $body_hover_color ?>; }

  .navbar {  border-width: 0pt }

  .foot1 {  
	color: #ffffff;
	font: 9pt arial,helvetica,sans-serif;
	text-decoration: none;
   }

a:link.nav1, a:visited.nav1, a:active.nav1{
	color: #ffffff;
	font: 9pt arial,helvetica,sans-serif;
	text-decoration: none;
}
a:hover.nav1{
	color: #B2B0B9;
	font: 9pt arial,helvetica,sans-serif;
	text-decoration: none;
}

  .foot {  
	border-color:<? echo $body_text_color ?>; 
  	border-width: 1px;
    background-color: #DAE6D2;
	padding-top: 1pt;
	padding-bottom: 3pt;
	font-size:10pt;
	margin-top: .15in;
   }
  .foot a:link { text-decoration: underline; color: #121212; }
  .foot a:visited { text-decoration: underline; color: #626262; }
  .foot a:hover { text-decoration: underline; color: <? echo $header_hover_color ?>; }


  .search1 a:link { text-decoration: underline; color: <? echo $header_text_color ?>; }
  .search1 a:visited { text-decoration: underline; color: <? echo $header_text_color ?>; }
  .search1 a:hover { text-decoration: underline; color: <? echo $header_hover_color ?>; }

  .search2 a:link { text-decoration: underline; color: <? echo $text_color ?>; font-size:8pt;}
  .search2 a:visited { text-decoration: underline; color: <? echo $text_color ?>; font-size:8pt;}
  .search2 a:hover { text-decoration: underline; color: <? echo $text_hover_color ?>; font-size:8pt;}

  input.search1 { 
  		border-color:<? echo $body_text_color ?>; 
  		border-width:1; 
  		font-family: verdana, trebuchet, arial, times; 
  		font-size:8pt;
        font-weight: bold; 
        background-color:#eeeeee; 
        color:<? echo $body_text_color ?>; }  
-->
</style>
